import { writeFileSync } from "node:fs";
const OB = "https://www.outlookbusiness.com/corporate/wipro-delayed-onboarding-of-over-250-freshers-nites-complains-to-labour-ministry";
const AIM = "https://analyticsindiamag.com/ai-news-updates/employee-union-flags-fresher-onboarding-delays-at-wipro-seeks-labour-ministry-intervention";
const END = 205.567;
const S = [];
const sc = (start, end, o) => S.push({ index: S.length, start, end: end ?? END, ...o });
const g = (card, grade = "cool") => ({ kind: "graphic", grade, ...(card ? { card } : {}) });
const br = (src, ms = 0, motion = "ken_in", grade = "cool") => ({ kind: "broll", src: `assets/broll/${src}.mp4`, media_start: ms, motion, grade, transition: "fade" });
sc(0, 6.07, br("delhi-govt", 3, "ken_in", "noir"));
sc(6.07, 13.92, { kind: "news", url: OB, source: "Outlook Business", headline: "Wipro Delayed Onboarding of Over 250 Freshers, NITES Complains to Labour Ministry", date: "19 Jan 2026", highlight: { x: 0.07, y: 0.262, w: 0.63, h: 0.062 }, highlight_portrait: undefined, motion: "ken_in", grade: "cool", transition: "cut" });
sc(13.92, 23.67, g({ value: "4", label: "things to know" }, "cool"));
sc(23.67, 27.7, g(null, "cool"));
sc(27.7, 33.54, g({ value: "NITES", label: "IT employees' union" }));
sc(33.54, 42.99, g(null));
sc(42.99, 48.89, { kind: "news", url: AIM, source: "Analytics India Magazine", headline: "Employee Union Flags Fresher Onboarding Delays at Wipro, Seeks Labour Ministry Intervention", date: "24 Jan 2026", highlight: { x: 0.04, y: 0.765, w: 0.5, h: 0.1 }, motion: "ken_in", grade: "cool", transition: "cut" });
sc(48.89, 56.22, g({ value: "May 2025", label: "letters of intent issued (reported)" }));
sc(56.22, 61.45, br("phone-wait", 1, "ken_out", "noir"));
sc(61.45, 64.23, g(null, "noir"));
sc(64.23, 74.41, g({ value: "Mint", label: "reported delays" }));
sc(74.41, 81.6, g({ value: "1", label: "Client caution" }, "cool"));
sc(81.6, 88.4, g({ value: "1", label: "Client caution" }, "noir"));
sc(88.4, 96.35, g({ value: "2", label: "A.I. + routine work" }, "cool"));
sc(96.35, 105.89, g({ value: "3", label: "Demand-based onboarding" }, "cool"));
sc(105.89, 109.0, g(null, "neutral"));
sc(109.0, 115.8, g(null, "neutral"));
sc(115.8, 122.0, g(null, "warm"));
sc(122.0, 128.5, g(null, "cool"));
sc(128.5, 137.78, g({ value: "No quick fix", label: "" }, "cool"));
sc(137.78, 141.66, g(null, "warm"));
sc(141.66, 150.09, br("writing-notes", 1, "pan_right", "warm"));
sc(150.09, 158.62, br("typing-email", 1, "ken_in", "warm"));
sc(158.62, 167.16, g({ value: "Keep applying", label: "" }, "warm"));
sc(167.16, 175.86, br("laptop-home", 2, "ken_in", "warm"));
sc(175.86, 183.5, g({ value: "Recap", label: "" }, "neutral"));
sc(183.5, 188.77, g(null, "cool"));
sc(188.77, 197.58, g(null, "neutral"));
sc(197.58, END, g(null, "neutral"));

const O = [];
const o = (start, end, type, p) => O.push({ start, duration: +(end - start).toFixed(2), type, ...p });
o(0.1, 3.2, "title_slide", { text: "Wipro Freshers vs the Labour Ministry", eyebrow: "Crack IT · Day 03", style_hint: "Onboarding delay, explained", value: "" });
o(3.3, 5.95, "number_roll", { value: 250, prefix: "", suffix: "+", text: "freshers with Wipro LOIs (reported)" });
o(7.2, 10.0, "keyword_chip", { text: "LABOUR MINISTRY", side: "right" });
o(10.5, 13.6, "side_note", { text: "Outlook Business · 19 Jan 2026", side: "right" });
o(14.5, 23.4, "bullet_list", { side: "right", text: "In this video", items: [{ label: "What happened" }, { label: "Why the delay" }, { label: "What the complaint can do" }, { label: "What you should do" }] });
o(24.5, 27.6, "chapter_open", { text: "What happened", eyebrow: "Section 01", numeral: "01", section: 1 });
o(27.9, 33.4, "term_card", { side: "left", text: "NITES", eyebrow: "IT employees' union", items: [{ label: "Nascent Information Technology Employees Senate — raises issues for IT employees" }] });
o(33.9, 42.4, "flow_diagram", { text: "The complaint", items: [{ label: "NITES", sublabel: "IT employees' union" }, { label: "Complaint", sublabel: "250+ freshers" }, { label: "Ministry of Labour", sublabel: "& Employment" }] });
o(44.0, 48.6, "keyword_chip", { text: "LOIs ~MAY 2025", side: "right" });
o(49.3, 56.0, "timeline", { side: "right", text: "The wait (reported)", current: 1, items: [{ label: "~May 2025", sublabel: "LOIs issued" }, { label: "Months on", sublabel: "not yet onboarded" }, { label: "Jan 2026", sublabel: "NITES complains" }] });
o(57.0, 60.6, "side_note", { text: "Other offers turned down", side: "left" });
o(61.55, 64.0, "big_statement", { text: "A gap on the resume", eyebrow: "gap" });
o(64.3, 67.4, "chapter_open", { text: "Why the delay", eyebrow: "Section 02", numeral: "02", section: 2 });
o(67.7, 74.2, "fact_band", { items: [{ label: "Cognizant", sublabel: "reported delay" }, { label: "Wipro", sublabel: "reported delay" }, { label: "LTM", sublabel: "reported delay" }] });
o(74.6, 79.9, "step_progress", { side: "right", text: "3 reasons (reported)", current_step: 0, items: [{ label: "Client caution" }, { label: "A.I. on routine work" }, { label: "Demand-based onboarding" }] });
o(80.6, 83.2, "keyword_chip", { text: "WEST ASIA TENSIONS", side: "right" });
o(85.7, 88.2, "side_note", { text: "Fewer projects = fewer seats", side: "left" });
o(88.9, 96.2, "term_card", { side: "left", text: "Routine work", eyebrow: "Reason 2", items: [{ label: "A.I. now handles basic testing, support and simple coding — work that used to go to new joiners" }] });
o(96.6, 99.7, "word_swap", { from: "Bulk hiring", to: "Demand-based", text: "how onboarding works now" });
o(100.2, 105.6, "flow_diagram", { text: "Demand-based", items: [{ label: "Campus pool", sublabel: "big batch hired" }, { label: "Project needs", sublabel: "a seat opens" }, { label: "Onboarded", sublabel: "only then" }] });
o(105.95, 109.0, "chapter_open", { text: "What it can do", eyebrow: "Section 03", numeral: "03", section: 3 });
o(110.3, 121.6, "checklist", { text: "What a complaint can do", items: [{ label: "Official attention", state: "yes" }, { label: "Clearer communication", state: "yes" }, { label: "Firmer timelines", state: "yes" }, { label: "A public record", state: "yes" }] });
o(122.3, 124.1, "keyword_chip", { text: "USUALLY CAN'T, QUICKLY", side: "left" });
o(124.5, 128.4, "big_statement", { text: "An LOI is not a contract", eyebrow: "LOI" });
o(129.0, 132.3, "side_note", { text: "Any outcome will take time", side: "left" });
o(133.0, 135.4, "annotation", { text: "Not a quick fix", shape: "underline", side: "right" });
o(138.1, 141.5, "chapter_open", { text: "What you should do", eyebrow: "Section 04", numeral: "04", section: 4 });
o(142.6, 149.9, "bullet_list", { side: "left", text: "1 · Keep a clean record", items: [{ label: "Letter of intent" }, { label: "Every email" }, { label: "Portal screenshots, with dates" }] });
o(152.9, 158.4, "sample_answer", { side: "right", text: "Subject: Onboarding timeline request\nCandidate ID: [your ID]\nRole: [your role]\nLOI date: [month, year]\nRequest: expected joining timeline" });
o(159.3, 161.1, "keyword_chip", { text: "KEEP APPLYING", side: "left" });
o(161.3, 163.7, "side_note", { text: "Protecting your career isn't disloyal", side: "right" });
o(164.0, 166.9, "big_statement", { text: "Make an informed choice", eyebrow: "informed" });
o(168.6, 175.6, "flow_diagram", { text: "4 · Use the wait", items: [{ label: "One strong skill" }, { label: "One real project" }, { label: "Ready either way" }] });
o(176.6, 182.4, "bullet_list", { side: "left", text: "To sum up", items: [{ label: "Union → Labour Ministry" }, { label: "Same delays at other companies" }, { label: "Attention, not a quick fix" }] });
o(185.2, 188.6, "big_statement", { text: "Your best protection is your own plan", eyebrow: "plan" });
o(189.0, 194.3, "quote_pull", { text: "Which company? Which LOI month?", eyebrow: "Comment below" });
o(194.8, 197.2, "marquee_strip", { text: "COMMENT · COMPANY · LOI MONTH", side: "left" });
o(198.0, 203.3, "big_statement", { text: "Tomorrow: LTIMindtree eligibility test", eyebrow: "Tomorrow" });
o(203.6, 205.4, "keyword_chip", { text: "SUBSCRIBE", side: "right" });

writeFileSync("work/visual-plan.json", JSON.stringify({ style: "blueprint", rail: true, overlays: O, scenes: S, camera_moves: [] }, null, 1));
