import { writeFileSync } from "node:fs";
const TNM = "https://www.thenewsminute.com/article/ltimindtree-revokes-offer-letters-freshers-mandates-new-training-programme-175698";
const HRK = "https://www.hrkatha.com/news/unions-speak-out-against-ltimindtrees-eligibility-test/";
const END = 230.867;
const S = [];
const sc = (start, end, o) => S.push({ index: S.length, start, end: end ?? END, ...o });
const g = (card, grade = "cool") => ({ kind: "graphic", grade, ...(card ? { card } : {}) });
const br = (src, ms = 0, motion = "ken_in", grade = "cool") => ({ kind: "broll", src: `assets/broll/${src}.mp4`, media_start: ms, motion, grade, transition: "fade" });
sc(0, 6.0, br("office", 0, "ken_in", "noir"));
sc(6.0, 10.92, g({ value: "Offer in hand", label: "test · interview · offer letter" }, "noir"));
sc(10.92, 15.5, g({ value: "2023", label: "the LTIMindtree case" }, "cool"));
sc(15.5, 20.0, g({ value: "2026", label: "reported again" }, "cool"));
sc(20.0, 24.5, br("phone", 1, "ken_out", "cool"));
sc(24.5, 31.7, g({ value: "3 questions", label: "what · why · how" }, "neutral"));
sc(31.7, 39.23, { kind: "news", url: TNM, source: "The News Minute", headline: "LTIMindtree revokes offer letters to freshers, mandates new training programme", date: "10 Apr 2023", highlight: { x: 0.1, y: 0.222, w: 0.54, h: 0.075 }, motion: "ken_in", grade: "cool", transition: "cut" });
sc(39.23, 44.46, br("waiting", 0, "pan_right", "noir"));
sc(44.46, 49.56, g({ value: "IGNITE", label: "2023 training programme" }, "cool"));
sc(49.56, 55.0, { kind: "news", url: HRK, source: "HRKatha", headline: "Unions speak out against LTIMindtree's eligibility test", date: "10 Apr 2023", highlight: { x: 0.08, y: 0.148, w: 0.54, h: 0.04 }, motion: "ken_in", grade: "cool", transition: "cut" });
sc(55.0, 59.78, g({ value: "60%", label: "in all three tests" }, "cool"));
sc(59.78, 64.5, g(null, "cool"));
sc(64.5, 69.02, g({ value: "Offers at risk", label: "reported by one outlet" }, "noir"));
sc(69.02, 77.85, g({ value: "NITES", label: "IT employees' union · 2023" }, "noir"));
sc(77.85, 83.3, g(null, "neutral"));
sc(83.3, 91.37, br("office", 3, "pan_left", "neutral"));
sc(91.37, 99.98, g({ value: "2", label: "Filtering" }, "cool"));
sc(99.98, 107.85, br("modules", 0, "ken_in", "warm"));
sc(107.85, 116.88, g(null, "neutral"));
sc(116.88, 120.23, g(null, "cool"));
sc(120.23, 128.41, br("study", 12, "ken_in", "cool"));
sc(128.41, 137.95, g({ value: "Cognizant", label: "candidate reports · 2026" }, "cool"));
sc(137.95, 142.72, g({ value: "Not official", label: "a candidate report" }, "warm"));
sc(142.72, 150.0, br("city", 0, "ken_in", "noir"));
sc(150.0, 153.67, g(null, "neutral"));
sc(153.67, 164.6, br("laptop", 0, "ken_out", "cool"));
sc(164.6, 174.42, br("study", 30, "pan_right", "warm"));
sc(174.42, 181.62, br("notes", 0, "ken_in", "cool"));
sc(181.62, 189.8, g({ value: "2 min", label: "explain your project" }, "warm"));
sc(189.8, 198.8, g({ value: "On time", label: "in writing" }, "warm"));
sc(198.8, 207.65, g(null, "neutral"));
sc(207.65, 215.5, g(null, "neutral"));
sc(215.5, 223.98, g(null, "cool"));
sc(223.98, END, g(null, "neutral"));

const O = [];
const o = (start, end, type, p) => O.push({ start, duration: +(end - start).toFixed(2), type, ...p });
o(0.1, 3.2, "title_slide", { text: "Another Test Before Joining?", eyebrow: "Crack IT · Day 04", style_hint: "The LTIMindtree case, 2023", value: "2023" });
o(3.6, 10.7, "checklist", { text: "You did everything right", items: [{ label: "Cleared the test", state: "yes" }, { label: "Cleared the interview", state: "yes" }, { label: "Offer letter in hand", state: "yes" }, { label: "One more test?", state: "no" }] });
o(11.2, 15.3, "keyword_chip", { text: "2023 CASE", side: "right" });
o(15.8, 19.8, "keyword_chip", { text: "2026 · PRE-JOINING TRAINING", side: "left" });
o(20.2, 23.6, "keyword_chip", { text: "KNOWLEDGE-TEST CALLS (REPORTED)", side: "right" });
o(24.5, 28.3, "bullet_list", { side: "right", text: "In this video", items: [{ label: "What happened" }, { label: "Why companies do it" }, { label: "How to clear it" }] });
o(28.55, 31.65, "chapter_open", { text: "What happened", eyebrow: "Section 01 · 2023", numeral: "01", section: 1 });
o(32.0, 35.2, "side_note", { text: "The News Minute · 10 Apr 2023", side: "right" });
o(35.6, 39.0, "keyword_chip", { text: "OFFERS ~JAN 2022", side: "right" });
o(39.5, 44.2, "timeline", { side: "right", text: "The wait · 2023 case", current: 1, items: [{ label: "~Jan 2022", sublabel: "offer letters" }, { label: "Over a year on", sublabel: "still waiting" }, { label: "Apr 2023", sublabel: "IGNITE announced" }] });
o(44.9, 49.4, "bullet_list", { side: "left", text: "IGNITE · 2023", items: [{ label: "6–7 weeks of training" }, { label: "3 assessment tests" }] });
o(49.9, 54.8, "keyword_chip", { text: "BATCHES · BUSINESS DEMAND", side: "right" });
o(55.2, 59.6, "side_note", { text: "Pass, then onboarded in batches", side: "left" });
o(60.3, 64.4, "big_statement", { text: "600–700 freshers (reported)", eyebrow: "600–700" });
o(64.8, 68.8, "keyword_chip", { text: "2023 · OFFERS COULD BE CANCELLED", side: "left" });
o(69.5, 77.6, "quote_pull", { text: "Not only unfair, but also a breach of trust", eyebrow: "NITES · via The News Minute, Apr 2023" });
o(78.1, 81.1, "chapter_open", { text: "Why companies do it", eyebrow: "Section 02", numeral: "02", section: 2 });
o(83.6, 91.2, "term_card", { side: "left", text: "Time", eyebrow: "Reason 1", items: [{ label: "Skills may be stale after a long wait, before a client project" }] });
o(92.0, 99.6, "flow_diagram", { text: "Filtering", items: [{ label: "Selected pool", sublabel: "more candidates" }, { label: "Open projects", sublabel: "fewer seats" }, { label: "A test decides", sublabel: "who goes first" }] });
o(100.3, 107.6, "term_card", { side: "right", text: "Readiness", eyebrow: "Reason 3", items: [{ label: "Trained on what projects need, so they become billable faster" }] });
o(108.4, 113.8, "comparison", { side: "right", left: { label: "Company view", text: "Check skills, pick who starts" }, right: { label: "Candidate view", text: "Already selected, why test?" } });
o(114.4, 116.7, "keyword_chip", { text: "UNDERSTAND IT, THEN PREPARE", side: "left" });
o(117.4, 120.4, "chapter_open", { text: "The 2026 link", eyebrow: "Section 03", numeral: "03", section: 3 });
o(120.8, 128.2, "bullet_list", { side: "right", text: "2026 · pre-joining", items: [{ label: "Training programmes" }, { label: "Online modules" }, { label: "For selected candidates" }] });
o(128.8, 137.6, "term_card", { side: "left", text: "Cognizant", eyebrow: "Candidate reports, 2026", items: [{ label: "HR calls with technical questions, like a short knowledge test, before offer or joining dates" }] });
o(138.0, 142.4, "keyword_chip", { text: "CANDIDATE REPORT, NOT OFFICIAL", side: "right" });
o(143.95, 146.2, "big_statement", { text: "Selection is not the finish line", eyebrow: "finish" });
o(146.6, 150.0, "side_note", { text: "Slow market: prove your skills again", side: "left" });
o(150.4, 153.5, "chapter_open", { text: "How to clear it", eyebrow: "Section 04", numeral: "04", section: 4 });
o(154.2, 164.4, "bullet_list", { side: "right", text: "1 · Revise the basics", items: [{ label: "Your programming language" }, { label: "Arrays and strings" }, { label: "SQL" }, { label: "OOP and DBMS" }] });
o(165.4, 171.2, "bullet_list", { side: "left", text: "2 · Take modules seriously", items: [{ label: "Finish them early" }, { label: "Take notes" }, { label: "Practise the quizzes" }] });
o(171.6, 174.3, "flow_diagram", { text: "Same source", items: [{ label: "Modules" }, { label: "The test" }] });
o(174.7, 177.3, "keyword_chip", { text: "3 · TIMED PRACTICE", side: "left" });
o(177.8, 181.2, "side_note", { text: "Speed matters as much as knowledge", side: "right" });
o(181.9, 184.2, "keyword_chip", { text: "4 · PROJECT READY", side: "right" });
o(184.8, 189.4, "side_note", { text: "A clear explanation makes an impression", side: "left" });
o(190.3, 195.0, "keyword_chip", { text: "RESPOND ON TIME, IN WRITING", side: "left" });
o(195.4, 198.6, "big_statement", { text: "A missed deadline can cost the offer", eyebrow: "deadline" });
o(199.2, 207.4, "bullet_list", { side: "left", text: "To sum up", items: [{ label: "2023 · IGNITE before joining" }, { label: "2026 · pre-joining checks again" }, { label: "Selection = halfway" }] });
o(207.9, 210.2, "keyword_chip", { text: "2026 · CHECKS ARE BACK", side: "right" });
o(210.5, 215.2, "big_statement", { text: "Treat selection as halfway", eyebrow: "halfway" });
o(216.0, 223.8, "quote_pull", { text: "Which company? What did they ask?", eyebrow: "Comment below" });
o(224.2, 229.0, "big_statement", { text: "Tomorrow: HCLTech results", eyebrow: "Tomorrow" });
o(229.3, 230.8, "keyword_chip", { text: "SUBSCRIBE", side: "right" });

writeFileSync("work/visual-plan.json", JSON.stringify({ style: "glass", rail: true, overlays: O, scenes: S, camera_moves: [] }, null, 1));
